---
# Playbook to Save Backup Configurations

- hosts: Routers

  tasks:
    - name: Backup Configurations
      ios_command:
        commands: show run
      register: config 

    - name: Save output to ~/ANS_OSPF/ansible-RHEL/backups
      copy:
        content: "{{config.stdout[0]}}"
        dest: "~/ANS_OSPF/ansible-RHEL/backups/{{inventory_hostname}}-backup.cfg"