---
## Playbook to Configure Things

- hosts: CSR_Routers

  tasks:
    - name: Configure a single command
      ios_config:
        lines: router ospf 1

    - name: Configure multiple lines of code from a text file
      ios_config:
        src: "~/Ansible/configs/config1.txt"

    - name: Save the config always
      ios_config:
        save_when: always