---
## Playbook to Configure Things

- hosts: Routers

  tasks:
    - name: Configure a single command
      ios_config:
        lines: service password-encryption

    - name: Configure multiple lines of code from a text file
      ios_config:
        src: "~/ANS_OSPF/ansible-RHEL/configs/config1.txt"

    - name: Save the config always
      ios_config:
        save_when: always