---
## Playbook to Show OSPF Neighbors on Routers

- hosts: Routers

  tasks:
    - name: Show OSPF Neighbors
      ios_command:
        commands: show ip ospf neighbor

      register: print_output

    - debug: var=print_output.stdout_lines