---

# Playbook to add Boot Statements and point to OS in Flash

- hosts: ios

  tasks:
     - name: Set Boot Statement
       ios_config:
         lines:
         - no boot system
         - boot system flash0:/vios_l2-adventerprisek9-m
         match: none
         save_when: always

- hosts: nxos

  tasks:
     - name: Set Boot Statement
       nxos_config:
         lines: boot nxos bootflash:nxos.9.3.3.bin
         match: none
         save_when: always
       vars:
         ansible_command_timeout: 60