---
## Playbook to Show Version on IOS - Save to file

- hosts: Routers

  tasks:
   - name: Show Version
     ios_command:
       commands: show version 
     register: version

   - name: Save output to ~/ANS_OSPF/ansible-RHEL/versions
     copy:
       content: "{{version.stdout[0]}}"
       dest: "~/ANS_OSPF/ansible-RHEL/versions/{{inventory_hostname}}-version.txt"