---
## Playbook to Show Version on IOS

- hosts: CSR_Routers

  tasks:
    - name: Show Version
      ios_command:
        commands: show version 

      register: print_output

    - debug: var=print_output.stdout_lines